// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listRulesForVehicleType = `-- name: ListRulesForVehicleType :many
SELECT
    sr.id              AS id,
    sr.part_id         AS part_id,
    sr.vehicle_type_id AS vehicle_type_id,
    sr.interval_km     AS interval_km,
    sr.interval_days   AS interval_days,
    sr.trigger_mode    AS trigger_mode,
    sr.notes           AS notes,
    sr.created_at      AS created_at,
    sr.updated_at      AS updated_at,
    p.name             AS part_name,
    p.slug             AS part_slug,
    p.category         AS part_category
FROM schedule_rules sr
JOIN maintenance_parts p ON p.id = sr.part_id
WHERE sr.vehicle_type_id = $1
ORDER BY p.name
`

type ListRulesForVehicleTypeRow struct {
	ID            uuid.UUID   `json:"id"`
	PartID        uuid.UUID   `json:"part_id"`
	VehicleTypeID uuid.UUID   `json:"vehicle_type_id"`
	IntervalKm    *int32      `json:"interval_km"`
	IntervalDays  *int32      `json:"interval_days"`
	TriggerMode   TriggerMode `json:"trigger_mode"`
	Notes         string      `json:"notes"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	PartName      string      `json:"part_name"`
	PartSlug      string      `json:"part_slug"`
	PartCategory  string      `json:"part_category"`
}

// Schedule rules enriched with their maintenance part, scoped to a vehicle type.
// Used by the alert computation to render part names alongside each rule.
func (q *Queries) ListRulesForVehicleType(ctx context.Context, vehicleTypeID uuid.UUID) ([]ListRulesForVehicleTypeRow, error) {
	rows, err := q.db.Query(ctx, listRulesForVehicleType, vehicleTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRulesForVehicleTypeRow
	for rows.Next() {
		var i ListRulesForVehicleTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.VehicleTypeID,
			&i.IntervalKm,
			&i.IntervalDays,
			&i.TriggerMode,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PartName,
			&i.PartSlug,
			&i.PartCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
