// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance_parts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countMaintenanceParts = `-- name: CountMaintenanceParts :one
SELECT count(*) FROM maintenance_parts
`

func (q *Queries) CountMaintenanceParts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMaintenanceParts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaintenancePart = `-- name: CreateMaintenancePart :one
INSERT INTO maintenance_parts (name, slug, category, description)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, category, description, created_at, updated_at
`

type CreateMaintenancePartParams struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Category    string `json:"category"`
	Description string `json:"description"`
}

func (q *Queries) CreateMaintenancePart(ctx context.Context, arg CreateMaintenancePartParams) (MaintenancePart, error) {
	row := q.db.QueryRow(ctx, createMaintenancePart,
		arg.Name,
		arg.Slug,
		arg.Category,
		arg.Description,
	)
	var i MaintenancePart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMaintenancePart = `-- name: DeleteMaintenancePart :exec
DELETE FROM maintenance_parts WHERE id = $1
`

func (q *Queries) DeleteMaintenancePart(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaintenancePart, id)
	return err
}

const getMaintenancePart = `-- name: GetMaintenancePart :one
SELECT id, name, slug, category, description, created_at, updated_at
FROM maintenance_parts
WHERE id = $1
`

func (q *Queries) GetMaintenancePart(ctx context.Context, id uuid.UUID) (MaintenancePart, error) {
	row := q.db.QueryRow(ctx, getMaintenancePart, id)
	var i MaintenancePart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMaintenanceParts = `-- name: ListMaintenanceParts :many
SELECT id, name, slug, category, description, created_at, updated_at
FROM maintenance_parts
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListMaintenancePartsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMaintenanceParts(ctx context.Context, arg ListMaintenancePartsParams) ([]MaintenancePart, error) {
	rows, err := q.db.Query(ctx, listMaintenanceParts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenancePart
	for rows.Next() {
		var i MaintenancePart
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenancePart = `-- name: UpdateMaintenancePart :one
UPDATE maintenance_parts
SET name = $2, slug = $3, category = $4, description = $5
WHERE id = $1
RETURNING id, name, slug, category, description, created_at, updated_at
`

type UpdateMaintenancePartParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Category    string    `json:"category"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateMaintenancePart(ctx context.Context, arg UpdateMaintenancePartParams) (MaintenancePart, error) {
	row := q.db.QueryRow(ctx, updateMaintenancePart,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Category,
		arg.Description,
	)
	var i MaintenancePart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
