// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance_records.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countAllMaintenanceRecords = `-- name: CountAllMaintenanceRecords :one
SELECT count(*) FROM maintenance_records
WHERE user_id = $1
  AND ($2::uuid IS NULL OR vehicle_id = $2)
`

type CountAllMaintenanceRecordsParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	VehicleID pgtype.UUID `json:"vehicle_id"`
}

func (q *Queries) CountAllMaintenanceRecords(ctx context.Context, arg CountAllMaintenanceRecordsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllMaintenanceRecords, arg.UserID, arg.VehicleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMaintenanceRecords = `-- name: CountMaintenanceRecords :one
SELECT count(*) FROM maintenance_records WHERE vehicle_id = $1 AND user_id = $2
`

type CountMaintenanceRecordsParams struct {
	VehicleID uuid.UUID `json:"vehicle_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CountMaintenanceRecords(ctx context.Context, arg CountMaintenanceRecordsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMaintenanceRecords, arg.VehicleID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaintenanceRecord = `-- name: CreateMaintenanceRecord :one
INSERT INTO maintenance_records (vehicle_id, part_id, user_id, performed_at, odometer_km, cost, technician, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, vehicle_id, part_id, user_id, performed_at, odometer_km, cost, technician, notes, created_at, updated_at
`

type CreateMaintenanceRecordParams struct {
	VehicleID   uuid.UUID       `json:"vehicle_id"`
	PartID      uuid.UUID       `json:"part_id"`
	UserID      uuid.UUID       `json:"user_id"`
	PerformedAt time.Time       `json:"performed_at"`
	OdometerKm  int32           `json:"odometer_km"`
	Cost        decimal.Decimal `json:"cost"`
	Technician  string          `json:"technician"`
	Notes       string          `json:"notes"`
}

func (q *Queries) CreateMaintenanceRecord(ctx context.Context, arg CreateMaintenanceRecordParams) (MaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, createMaintenanceRecord,
		arg.VehicleID,
		arg.PartID,
		arg.UserID,
		arg.PerformedAt,
		arg.OdometerKm,
		arg.Cost,
		arg.Technician,
		arg.Notes,
	)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.PartID,
		&i.UserID,
		&i.PerformedAt,
		&i.OdometerKm,
		&i.Cost,
		&i.Technician,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMaintenanceRecord = `-- name: DeleteMaintenanceRecord :exec
DELETE FROM maintenance_records WHERE id = $1 AND user_id = $2
`

type DeleteMaintenanceRecordParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMaintenanceRecord(ctx context.Context, arg DeleteMaintenanceRecordParams) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceRecord, arg.ID, arg.UserID)
	return err
}

const getMaintenanceRecord = `-- name: GetMaintenanceRecord :one
SELECT id, vehicle_id, part_id, user_id, performed_at, odometer_km, cost, technician, notes, created_at, updated_at
FROM maintenance_records
WHERE id = $1 AND user_id = $2
`

type GetMaintenanceRecordParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMaintenanceRecord(ctx context.Context, arg GetMaintenanceRecordParams) (MaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, getMaintenanceRecord, arg.ID, arg.UserID)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.PartID,
		&i.UserID,
		&i.PerformedAt,
		&i.OdometerKm,
		&i.Cost,
		&i.Technician,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestRecordPerPart = `-- name: LatestRecordPerPart :many
SELECT DISTINCT ON (part_id)
       part_id,
       id,
       vehicle_id,
       user_id,
       performed_at,
       odometer_km,
       cost,
       technician,
       notes,
       created_at,
       updated_at
FROM maintenance_records
WHERE vehicle_id = $1 AND user_id = $2
ORDER BY part_id, performed_at DESC, odometer_km DESC
`

type LatestRecordPerPartParams struct {
	VehicleID uuid.UUID `json:"vehicle_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type LatestRecordPerPartRow struct {
	PartID      uuid.UUID       `json:"part_id"`
	ID          uuid.UUID       `json:"id"`
	VehicleID   uuid.UUID       `json:"vehicle_id"`
	UserID      uuid.UUID       `json:"user_id"`
	PerformedAt time.Time       `json:"performed_at"`
	OdometerKm  int32           `json:"odometer_km"`
	Cost        decimal.Decimal `json:"cost"`
	Technician  string          `json:"technician"`
	Notes       string          `json:"notes"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

// Latest record per part for a vehicle — used by the alert computation.
func (q *Queries) LatestRecordPerPart(ctx context.Context, arg LatestRecordPerPartParams) ([]LatestRecordPerPartRow, error) {
	rows, err := q.db.Query(ctx, latestRecordPerPart, arg.VehicleID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestRecordPerPartRow
	for rows.Next() {
		var i LatestRecordPerPartRow
		if err := rows.Scan(
			&i.PartID,
			&i.ID,
			&i.VehicleID,
			&i.UserID,
			&i.PerformedAt,
			&i.OdometerKm,
			&i.Cost,
			&i.Technician,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMaintenanceRecords = `-- name: ListAllMaintenanceRecords :many
SELECT id, vehicle_id, part_id, user_id, performed_at, odometer_km, cost, technician, notes, created_at, updated_at
FROM maintenance_records
WHERE user_id = $1
  AND ($4::uuid IS NULL OR vehicle_id = $4)
ORDER BY performed_at DESC
LIMIT $2 OFFSET $3
`

type ListAllMaintenanceRecordsParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	VehicleID pgtype.UUID `json:"vehicle_id"`
}

func (q *Queries) ListAllMaintenanceRecords(ctx context.Context, arg ListAllMaintenanceRecordsParams) ([]MaintenanceRecord, error) {
	rows, err := q.db.Query(ctx, listAllMaintenanceRecords,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.VehicleID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceRecord
	for rows.Next() {
		var i MaintenanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.PartID,
			&i.UserID,
			&i.PerformedAt,
			&i.OdometerKm,
			&i.Cost,
			&i.Technician,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceRecords = `-- name: ListMaintenanceRecords :many
SELECT mr.id, mr.vehicle_id, mr.part_id, mr.user_id, mr.performed_at, mr.odometer_km, mr.cost, mr.technician, mr.notes, mr.created_at, mr.updated_at
FROM maintenance_records mr
WHERE mr.vehicle_id = $1 AND mr.user_id = $2
ORDER BY mr.performed_at DESC
LIMIT $3 OFFSET $4
`

type ListMaintenanceRecordsParams struct {
	VehicleID uuid.UUID `json:"vehicle_id"`
	UserID    uuid.UUID `json:"user_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListMaintenanceRecords(ctx context.Context, arg ListMaintenanceRecordsParams) ([]MaintenanceRecord, error) {
	rows, err := q.db.Query(ctx, listMaintenanceRecords,
		arg.VehicleID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaintenanceRecord
	for rows.Next() {
		var i MaintenanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.PartID,
			&i.UserID,
			&i.PerformedAt,
			&i.OdometerKm,
			&i.Cost,
			&i.Technician,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenanceRecord = `-- name: UpdateMaintenanceRecord :one
UPDATE maintenance_records
SET part_id      = $3,
    performed_at = $4,
    odometer_km  = $5,
    cost         = $6,
    technician   = $7,
    notes        = $8
WHERE id = $1 AND user_id = $2
RETURNING id, vehicle_id, part_id, user_id, performed_at, odometer_km, cost, technician, notes, created_at, updated_at
`

type UpdateMaintenanceRecordParams struct {
	ID          uuid.UUID       `json:"id"`
	UserID      uuid.UUID       `json:"user_id"`
	PartID      uuid.UUID       `json:"part_id"`
	PerformedAt time.Time       `json:"performed_at"`
	OdometerKm  int32           `json:"odometer_km"`
	Cost        decimal.Decimal `json:"cost"`
	Technician  string          `json:"technician"`
	Notes       string          `json:"notes"`
}

func (q *Queries) UpdateMaintenanceRecord(ctx context.Context, arg UpdateMaintenanceRecordParams) (MaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, updateMaintenanceRecord,
		arg.ID,
		arg.UserID,
		arg.PartID,
		arg.PerformedAt,
		arg.OdometerKm,
		arg.Cost,
		arg.Technician,
		arg.Notes,
	)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.PartID,
		&i.UserID,
		&i.PerformedAt,
		&i.OdometerKm,
		&i.Cost,
		&i.Technician,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
