// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type TriggerMode string

const (
	TriggerModeOr       TriggerMode = "or"
	TriggerModeAnd      TriggerMode = "and"
	TriggerModeKmOnly   TriggerMode = "km_only"
	TriggerModeDateOnly TriggerMode = "date_only"
)

func (e *TriggerMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TriggerMode(s)
	case string:
		*e = TriggerMode(s)
	default:
		return fmt.Errorf("unsupported scan type for TriggerMode: %T", src)
	}
	return nil
}

type NullTriggerMode struct {
	TriggerMode TriggerMode `json:"trigger_mode"`
	Valid       bool        `json:"valid"` // Valid is true if TriggerMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTriggerMode) Scan(value interface{}) error {
	if value == nil {
		ns.TriggerMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TriggerMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTriggerMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TriggerMode), nil
}

func (e TriggerMode) Valid() bool {
	switch e {
	case TriggerModeOr,
		TriggerModeAnd,
		TriggerModeKmOnly,
		TriggerModeDateOnly:
		return true
	}
	return false
}

func AllTriggerModeValues() []TriggerMode {
	return []TriggerMode{
		TriggerModeOr,
		TriggerModeAnd,
		TriggerModeKmOnly,
		TriggerModeDateOnly,
	}
}

type MaintenancePart struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Category    string    `json:"category"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type MaintenanceRecord struct {
	ID          uuid.UUID       `json:"id"`
	VehicleID   uuid.UUID       `json:"vehicle_id"`
	PartID      uuid.UUID       `json:"part_id"`
	UserID      uuid.UUID       `json:"user_id"`
	PerformedAt time.Time       `json:"performed_at"`
	OdometerKm  int32           `json:"odometer_km"`
	Cost        decimal.Decimal `json:"cost"`
	Technician  string          `json:"technician"`
	Notes       string          `json:"notes"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type ScheduleRule struct {
	ID            uuid.UUID   `json:"id"`
	PartID        uuid.UUID   `json:"part_id"`
	VehicleTypeID uuid.UUID   `json:"vehicle_type_id"`
	IntervalKm    *int32      `json:"interval_km"`
	IntervalDays  *int32      `json:"interval_days"`
	TriggerMode   TriggerMode `json:"trigger_mode"`
	Notes         string      `json:"notes"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Vehicle struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	VehicleTypeID     uuid.UUID `json:"vehicle_type_id"`
	PlateNumber       string    `json:"plate_number"`
	Brand             string    `json:"brand"`
	Model             string    `json:"model"`
	Year              *int32    `json:"year"`
	CurrentOdometerKm int32     `json:"current_odometer_km"`
	Notes             string    `json:"notes"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	InitialOdometerKm int32     `json:"initial_odometer_km"`
}

type VehicleType struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
