// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountAllMaintenanceRecords(ctx context.Context, arg CountAllMaintenanceRecordsParams) (int64, error)
	CountMaintenanceParts(ctx context.Context) (int64, error)
	CountMaintenanceRecords(ctx context.Context, arg CountMaintenanceRecordsParams) (int64, error)
	CountScheduleRules(ctx context.Context) (int64, error)
	CountVehicleTypes(ctx context.Context) (int64, error)
	CountVehicles(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateMaintenancePart(ctx context.Context, arg CreateMaintenancePartParams) (MaintenancePart, error)
	CreateMaintenanceRecord(ctx context.Context, arg CreateMaintenanceRecordParams) (MaintenanceRecord, error)
	CreateScheduleRule(ctx context.Context, arg CreateScheduleRuleParams) (ScheduleRule, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error)
	CreateVehicleType(ctx context.Context, arg CreateVehicleTypeParams) (VehicleType, error)
	DeleteMaintenancePart(ctx context.Context, id uuid.UUID) error
	DeleteMaintenanceRecord(ctx context.Context, arg DeleteMaintenanceRecordParams) error
	DeleteScheduleRule(ctx context.Context, id uuid.UUID) error
	DeleteVehicle(ctx context.Context, arg DeleteVehicleParams) error
	DeleteVehicleType(ctx context.Context, id uuid.UUID) error
	GetMaintenancePart(ctx context.Context, id uuid.UUID) (MaintenancePart, error)
	GetMaintenanceRecord(ctx context.Context, arg GetMaintenanceRecordParams) (MaintenanceRecord, error)
	GetScheduleRule(ctx context.Context, id uuid.UUID) (ScheduleRule, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVehicle(ctx context.Context, arg GetVehicleParams) (Vehicle, error)
	GetVehicleType(ctx context.Context, id uuid.UUID) (VehicleType, error)
	// Latest record per part for a vehicle — used by the alert computation.
	LatestRecordPerPart(ctx context.Context, arg LatestRecordPerPartParams) ([]LatestRecordPerPartRow, error)
	ListAllMaintenanceRecords(ctx context.Context, arg ListAllMaintenanceRecordsParams) ([]MaintenanceRecord, error)
	ListMaintenanceParts(ctx context.Context, arg ListMaintenancePartsParams) ([]MaintenancePart, error)
	ListMaintenanceRecords(ctx context.Context, arg ListMaintenanceRecordsParams) ([]MaintenanceRecord, error)
	// Schedule rules enriched with their maintenance part, scoped to a vehicle type.
	// Used by the alert computation to render part names alongside each rule.
	ListRulesForVehicleType(ctx context.Context, vehicleTypeID uuid.UUID) ([]ListRulesForVehicleTypeRow, error)
	ListScheduleRules(ctx context.Context, arg ListScheduleRulesParams) ([]ScheduleRule, error)
	ListScheduleRulesByVehicleType(ctx context.Context, vehicleTypeID uuid.UUID) ([]ScheduleRule, error)
	ListVehicleTypes(ctx context.Context, arg ListVehicleTypesParams) ([]VehicleType, error)
	ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]Vehicle, error)
	UpdateMaintenancePart(ctx context.Context, arg UpdateMaintenancePartParams) (MaintenancePart, error)
	UpdateMaintenanceRecord(ctx context.Context, arg UpdateMaintenanceRecordParams) (MaintenanceRecord, error)
	UpdateScheduleRule(ctx context.Context, arg UpdateScheduleRuleParams) (ScheduleRule, error)
	UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error)
	UpdateVehicleOdometerIfHigher(ctx context.Context, arg UpdateVehicleOdometerIfHigherParams) (Vehicle, error)
	UpdateVehicleType(ctx context.Context, arg UpdateVehicleTypeParams) (VehicleType, error)
}

var _ Querier = (*Queries)(nil)
