// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule_rules.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countScheduleRules = `-- name: CountScheduleRules :one
SELECT count(*) FROM schedule_rules
`

func (q *Queries) CountScheduleRules(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countScheduleRules)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScheduleRule = `-- name: CreateScheduleRule :one
INSERT INTO schedule_rules (part_id, vehicle_type_id, interval_km, interval_days, trigger_mode, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, part_id, vehicle_type_id, interval_km, interval_days, trigger_mode, notes, created_at, updated_at
`

type CreateScheduleRuleParams struct {
	PartID        uuid.UUID   `json:"part_id"`
	VehicleTypeID uuid.UUID   `json:"vehicle_type_id"`
	IntervalKm    *int32      `json:"interval_km"`
	IntervalDays  *int32      `json:"interval_days"`
	TriggerMode   TriggerMode `json:"trigger_mode"`
	Notes         string      `json:"notes"`
}

func (q *Queries) CreateScheduleRule(ctx context.Context, arg CreateScheduleRuleParams) (ScheduleRule, error) {
	row := q.db.QueryRow(ctx, createScheduleRule,
		arg.PartID,
		arg.VehicleTypeID,
		arg.IntervalKm,
		arg.IntervalDays,
		arg.TriggerMode,
		arg.Notes,
	)
	var i ScheduleRule
	err := row.Scan(
		&i.ID,
		&i.PartID,
		&i.VehicleTypeID,
		&i.IntervalKm,
		&i.IntervalDays,
		&i.TriggerMode,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScheduleRule = `-- name: DeleteScheduleRule :exec
DELETE FROM schedule_rules WHERE id = $1
`

func (q *Queries) DeleteScheduleRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScheduleRule, id)
	return err
}

const getScheduleRule = `-- name: GetScheduleRule :one
SELECT id, part_id, vehicle_type_id, interval_km, interval_days, trigger_mode, notes, created_at, updated_at
FROM schedule_rules
WHERE id = $1
`

func (q *Queries) GetScheduleRule(ctx context.Context, id uuid.UUID) (ScheduleRule, error) {
	row := q.db.QueryRow(ctx, getScheduleRule, id)
	var i ScheduleRule
	err := row.Scan(
		&i.ID,
		&i.PartID,
		&i.VehicleTypeID,
		&i.IntervalKm,
		&i.IntervalDays,
		&i.TriggerMode,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScheduleRules = `-- name: ListScheduleRules :many
SELECT id, part_id, vehicle_type_id, interval_km, interval_days, trigger_mode, notes, created_at, updated_at
FROM schedule_rules
ORDER BY created_at
LIMIT $1 OFFSET $2
`

type ListScheduleRulesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListScheduleRules(ctx context.Context, arg ListScheduleRulesParams) ([]ScheduleRule, error) {
	rows, err := q.db.Query(ctx, listScheduleRules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleRule
	for rows.Next() {
		var i ScheduleRule
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.VehicleTypeID,
			&i.IntervalKm,
			&i.IntervalDays,
			&i.TriggerMode,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleRulesByVehicleType = `-- name: ListScheduleRulesByVehicleType :many
SELECT id, part_id, vehicle_type_id, interval_km, interval_days, trigger_mode, notes, created_at, updated_at
FROM schedule_rules
WHERE vehicle_type_id = $1
ORDER BY created_at
`

func (q *Queries) ListScheduleRulesByVehicleType(ctx context.Context, vehicleTypeID uuid.UUID) ([]ScheduleRule, error) {
	rows, err := q.db.Query(ctx, listScheduleRulesByVehicleType, vehicleTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleRule
	for rows.Next() {
		var i ScheduleRule
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.VehicleTypeID,
			&i.IntervalKm,
			&i.IntervalDays,
			&i.TriggerMode,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleRule = `-- name: UpdateScheduleRule :one
UPDATE schedule_rules
SET part_id = $2,
    vehicle_type_id = $3,
    interval_km = $4,
    interval_days = $5,
    trigger_mode = $6,
    notes = $7
WHERE id = $1
RETURNING id, part_id, vehicle_type_id, interval_km, interval_days, trigger_mode, notes, created_at, updated_at
`

type UpdateScheduleRuleParams struct {
	ID            uuid.UUID   `json:"id"`
	PartID        uuid.UUID   `json:"part_id"`
	VehicleTypeID uuid.UUID   `json:"vehicle_type_id"`
	IntervalKm    *int32      `json:"interval_km"`
	IntervalDays  *int32      `json:"interval_days"`
	TriggerMode   TriggerMode `json:"trigger_mode"`
	Notes         string      `json:"notes"`
}

func (q *Queries) UpdateScheduleRule(ctx context.Context, arg UpdateScheduleRuleParams) (ScheduleRule, error) {
	row := q.db.QueryRow(ctx, updateScheduleRule,
		arg.ID,
		arg.PartID,
		arg.VehicleTypeID,
		arg.IntervalKm,
		arg.IntervalDays,
		arg.TriggerMode,
		arg.Notes,
	)
	var i ScheduleRule
	err := row.Scan(
		&i.ID,
		&i.PartID,
		&i.VehicleTypeID,
		&i.IntervalKm,
		&i.IntervalDays,
		&i.TriggerMode,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
