// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicles.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countVehicles = `-- name: CountVehicles :one
SELECT count(*) FROM vehicles WHERE user_id = $1
`

func (q *Queries) CountVehicles(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVehicles, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (user_id, vehicle_type_id, plate_number, brand, model, year, current_odometer_km, initial_odometer_km, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, vehicle_type_id, plate_number, brand, model, year, current_odometer_km, notes, created_at, updated_at, initial_odometer_km
`

type CreateVehicleParams struct {
	UserID            uuid.UUID `json:"user_id"`
	VehicleTypeID     uuid.UUID `json:"vehicle_type_id"`
	PlateNumber       string    `json:"plate_number"`
	Brand             string    `json:"brand"`
	Model             string    `json:"model"`
	Year              *int32    `json:"year"`
	CurrentOdometerKm int32     `json:"current_odometer_km"`
	InitialOdometerKm int32     `json:"initial_odometer_km"`
	Notes             string    `json:"notes"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.UserID,
		arg.VehicleTypeID,
		arg.PlateNumber,
		arg.Brand,
		arg.Model,
		arg.Year,
		arg.CurrentOdometerKm,
		arg.InitialOdometerKm,
		arg.Notes,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleTypeID,
		&i.PlateNumber,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.CurrentOdometerKm,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialOdometerKm,
	)
	return i, err
}

const deleteVehicle = `-- name: DeleteVehicle :exec
DELETE FROM vehicles WHERE id = $1 AND user_id = $2
`

type DeleteVehicleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteVehicle(ctx context.Context, arg DeleteVehicleParams) error {
	_, err := q.db.Exec(ctx, deleteVehicle, arg.ID, arg.UserID)
	return err
}

const getVehicle = `-- name: GetVehicle :one
SELECT id, user_id, vehicle_type_id, plate_number, brand, model, year, current_odometer_km, notes, created_at, updated_at, initial_odometer_km
FROM vehicles
WHERE id = $1 AND user_id = $2
`

type GetVehicleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetVehicle(ctx context.Context, arg GetVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicle, arg.ID, arg.UserID)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleTypeID,
		&i.PlateNumber,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.CurrentOdometerKm,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialOdometerKm,
	)
	return i, err
}

const listVehicles = `-- name: ListVehicles :many
SELECT id, user_id, vehicle_type_id, plate_number, brand, model, year, current_odometer_km, notes, created_at, updated_at, initial_odometer_km
FROM vehicles
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVehiclesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehicles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehicle
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VehicleTypeID,
			&i.PlateNumber,
			&i.Brand,
			&i.Model,
			&i.Year,
			&i.CurrentOdometerKm,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InitialOdometerKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET vehicle_type_id = $3,
    plate_number    = $4,
    brand           = $5,
    model           = $6,
    year            = $7,
    notes           = $8
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, vehicle_type_id, plate_number, brand, model, year, current_odometer_km, notes, created_at, updated_at, initial_odometer_km
`

type UpdateVehicleParams struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	VehicleTypeID uuid.UUID `json:"vehicle_type_id"`
	PlateNumber   string    `json:"plate_number"`
	Brand         string    `json:"brand"`
	Model         string    `json:"model"`
	Year          *int32    `json:"year"`
	Notes         string    `json:"notes"`
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicle,
		arg.ID,
		arg.UserID,
		arg.VehicleTypeID,
		arg.PlateNumber,
		arg.Brand,
		arg.Model,
		arg.Year,
		arg.Notes,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleTypeID,
		&i.PlateNumber,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.CurrentOdometerKm,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialOdometerKm,
	)
	return i, err
}

const updateVehicleOdometerIfHigher = `-- name: UpdateVehicleOdometerIfHigher :one
UPDATE vehicles
SET current_odometer_km = $3
WHERE id = $1 AND user_id = $2 AND $3 > current_odometer_km
RETURNING id, user_id, vehicle_type_id, plate_number, brand, model, year, current_odometer_km, notes, created_at, updated_at, initial_odometer_km
`

type UpdateVehicleOdometerIfHigherParams struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	CurrentOdometerKm int32     `json:"current_odometer_km"`
}

func (q *Queries) UpdateVehicleOdometerIfHigher(ctx context.Context, arg UpdateVehicleOdometerIfHigherParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicleOdometerIfHigher, arg.ID, arg.UserID, arg.CurrentOdometerKm)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleTypeID,
		&i.PlateNumber,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.CurrentOdometerKm,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialOdometerKm,
	)
	return i, err
}
