// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicle_types.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countVehicleTypes = `-- name: CountVehicleTypes :one
SELECT count(*) FROM vehicle_types
`

func (q *Queries) CountVehicleTypes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countVehicleTypes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVehicleType = `-- name: CreateVehicleType :one
INSERT INTO vehicle_types (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, updated_at
`

type CreateVehicleTypeParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateVehicleType(ctx context.Context, arg CreateVehicleTypeParams) (VehicleType, error) {
	row := q.db.QueryRow(ctx, createVehicleType, arg.Name, arg.Slug)
	var i VehicleType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVehicleType = `-- name: DeleteVehicleType :exec
DELETE FROM vehicle_types WHERE id = $1
`

func (q *Queries) DeleteVehicleType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVehicleType, id)
	return err
}

const getVehicleType = `-- name: GetVehicleType :one
SELECT id, name, slug, created_at, updated_at
FROM vehicle_types
WHERE id = $1
`

func (q *Queries) GetVehicleType(ctx context.Context, id uuid.UUID) (VehicleType, error) {
	row := q.db.QueryRow(ctx, getVehicleType, id)
	var i VehicleType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVehicleTypes = `-- name: ListVehicleTypes :many
SELECT id, name, slug, created_at, updated_at
FROM vehicle_types
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListVehicleTypesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVehicleTypes(ctx context.Context, arg ListVehicleTypesParams) ([]VehicleType, error) {
	rows, err := q.db.Query(ctx, listVehicleTypes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleType
	for rows.Next() {
		var i VehicleType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicleType = `-- name: UpdateVehicleType :one
UPDATE vehicle_types
SET name = $2, slug = $3
WHERE id = $1
RETURNING id, name, slug, created_at, updated_at
`

type UpdateVehicleTypeParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) UpdateVehicleType(ctx context.Context, arg UpdateVehicleTypeParams) (VehicleType, error) {
	row := q.db.QueryRow(ctx, updateVehicleType, arg.ID, arg.Name, arg.Slug)
	var i VehicleType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
